import { Category, Professional, Review } from './types';

export const CATEGORIES: Category[] = [
  { id: 'limpeza', name: 'Limpeza', icon: 'cleaning_services' },
  { id: 'reparos', name: 'Reparos', icon: 'plumbing' },
  { id: 'beleza', name: 'Beleza', icon: 'spa' },
  { id: 'aulas', name: 'Aulas', icon: 'school' },
  { id: 'fretes', name: 'Fretes', icon: 'local_shipping' },
  { id: 'ti', name: 'T.I.', icon: 'computer' },
  { id: 'pet', name: 'Pet', icon: 'pets' },
  { id: 'barbearia', name: 'Barbearia', icon: 'content_cut' },
];

export const PROFESSIONALS: Professional[] = [
  {
    id: 'p1',
    name: 'Maria Silva',
    profession: 'Diarista & Especialista em Organização',
    description: 'Mais de 8 anos de experiência em limpeza residencial e empresarial profunda, pós-obra e organização de ambientes com técnicas avançadas.',
    categoryId: 'limpeza',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&h=200&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=600&h=300&fit=crop',
    rating: 4.9,
    reviewsCount: 148,
    verified: true,
    activeSubscription: true,
    location: 'São Paulo, SP',
    services: [
      {
        id: 's1-1',
        professionalId: 'p1',
        title: 'Faxina Residencial Completa',
        description: 'Limpeza detalhada de todos os cômodos, banheiros, vidros e cozinha.',
        category: 'Limpeza',
        price: 180,
        duration: 240,
      },
      {
        id: 's1-2',
        professionalId: 'p1',
        title: 'Limpeza Pós-Obra',
        description: 'Remoção minuciosa de poeira fina, manchas de tinta e resíduos de reforma.',
        category: 'Limpeza',
        price: 320,
        duration: 360,
      },
      {
        id: 's1-3',
        professionalId: 'p1',
        title: 'Organização de Ambientes (Personal Organizer)',
        description: 'Otimização de closets, armários de cozinha e descarte consciente.',
        category: 'Limpeza',
        price: 150,
        duration: 180,
      },
    ],
  },
  {
    id: 'p2',
    name: 'Carlos Eduardo Mendes',
    profession: 'Eletricista & Encanador Residencial',
    description: 'Técnico certificado em instalações elétricas de baixa e média tensão, quadros de distribuição, reparos hidráulicos e detecção de vazamentos.',
    categoryId: 'reparos',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=600&h=300&fit=crop',
    rating: 4.95,
    reviewsCount: 92,
    verified: true,
    activeSubscription: true,
    location: 'Rio de Janeiro, RJ',
    services: [
      {
        id: 's2-1',
        professionalId: 'p2',
        title: 'Instalação de Chuveiro / Tomadas 220V',
        description: 'Troca de fiação antiga, disjuntor dedicado e instalação com segurança.',
        category: 'Reparos',
        price: 90,
        duration: 60,
      },
      {
        id: 's2-2',
        professionalId: 'p2',
        title: 'Reparo Hidráulico & Troca de Registro',
        description: 'Solução rápida para vazamentos em pias, vasos sanitários e chuveiros.',
        category: 'Reparos',
        price: 120,
        duration: 90,
      },
      {
        id: 's2-3',
        professionalId: 'p2',
        title: 'Revisão Geral do Quadro Elétrico',
        description: 'Diagnóstico térmico, balanceamento de circuitos e substituição de disjuntores.',
        category: 'Reparos',
        price: 200,
        duration: 120,
      },
    ],
  },
  {
    id: 'p3',
    name: 'Juliana Barbosa',
    profession: 'Designer de Sobrancelhas & Esteticista',
    description: 'Especialista em visagismo facial, micropigmentação fio a fio, lash lifting e limpeza de pele com produtos hipoalergênicos e tecnologia de ponta.',
    categoryId: 'beleza',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&h=200&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1560750588-73207b1ef5b8?w=600&h=300&fit=crop',
    rating: 5.0,
    reviewsCount: 215,
    verified: true,
    activeSubscription: true,
    location: 'Belo Horizonte, MG',
    services: [
      {
        id: 's3-1',
        professionalId: 'p3',
        title: 'Design de Sobrancelhas com Henna',
        description: 'Mapeamento facial com paquímetro e aplicação personalizada de pigmento vegetal.',
        category: 'Beleza',
        price: 55,
        duration: 45,
      },
      {
        id: 's3-2',
        professionalId: 'p3',
        title: 'Lash Lifting & Nutrição de Cílios',
        description: 'Curvatura e hidratação profunda para cílios naturais volumosos por até 6 semanas.',
        category: 'Beleza',
        price: 110,
        duration: 60,
      },
      {
        id: 's3-3',
        professionalId: 'p3',
        title: 'Limpeza de Pele Profunda com Ozônio',
        description: 'Vapor de ozônio, extração de comedões por sucção e máscara calmante de LED.',
        category: 'Beleza',
        price: 140,
        duration: 90,
      },
    ],
  },
  {
    id: 'p4',
    name: 'Lucas Ferreira',
    profession: 'Barbeiro & Visagista Masculino',
    description: 'Cortes modernos degradê (fade), barba na toalha quente com óleos essenciais, pigmentação de barba e alinhamento capilar.',
    categoryId: 'barbearia',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=600&h=300&fit=crop',
    rating: 4.85,
    reviewsCount: 78,
    verified: true,
    activeSubscription: true,
    location: 'Curitiba, PR',
    services: [
      {
        id: 's4-1',
        professionalId: 'p4',
        title: 'Corte Degradê Fade & Freestyle',
        description: 'Acabamento preciso na navalha, degradê suave e finalização com pomada matte.',
        category: 'Barbearia',
        price: 50,
        duration: 40,
      },
      {
        id: 's4-2',
        professionalId: 'p4',
        title: 'Barboterapia com Toalha Quente',
        description: 'Esfoliação suave, navalhamento clássico, toalha quente aromática e pós-barba.',
        category: 'Barbearia',
        price: 45,
        duration: 35,
      },
      {
        id: 's4-3',
        professionalId: 'p4',
        title: 'Combo Cabelo + Barba Completa',
        description: 'Pacote completo de corte estilizado e barba alinhada com hidratação.',
        category: 'Barbearia',
        price: 85,
        duration: 70,
      },
    ],
  },
  {
    id: 'p5',
    name: 'Rafael Guimarães',
    profession: 'Especialista em T.I., Redes & Hardware',
    description: 'Mais de 10 anos prestando assistência técnica para computadores, notebooks, montagem de PCs gamer, servidores locais e infraestrutura de rede.',
    categoryId: 'ti',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&h=200&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&h=300&fit=crop',
    rating: 4.92,
    reviewsCount: 64,
    verified: true,
    activeSubscription: true,
    location: 'Campinas, SP',
    services: [
      {
        id: 's5-1',
        professionalId: 'p5',
        title: 'Formatação, Otimização & Backup',
        description: 'Instalação limpa do Windows/Linux com drivers atualizados e backup seguro de arquivos.',
        category: 'T.I.',
        price: 130,
        duration: 90,
      },
      {
        id: 's5-2',
        professionalId: 'p5',
        title: 'Configuração de Rede Mesh / Wi-Fi',
        description: 'Eliminação de pontos cegos de internet e configuração de segurança WPA3.',
        category: 'T.I.',
        price: 160,
        duration: 60,
      },
      {
        id: 's5-3',
        professionalId: 'p5',
        title: 'Limpeza Preventiva & Troca de Pasta Térmica',
        description: 'Desoxidação de componentes, troca de thermal pads e pasta térmica de prata.',
        category: 'T.I.',
        price: 110,
        duration: 60,
      },
    ],
  },
  {
    id: 'p6',
    name: 'Beatriz Nogueira',
    profession: 'Professora Particular de Idiomas (Inglês & Espanhol)',
    description: 'Graduada em Letras com vivência no exterior. Aulas dinâmicas e focadas em conversação real, preparação para entrevistas e certificações internacionais.',
    categoryId: 'aulas',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&h=200&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=600&h=300&fit=crop',
    rating: 4.98,
    reviewsCount: 112,
    verified: true,
    activeSubscription: true,
    location: 'Porto Alegre, RS',
    services: [
      {
        id: 's6-1',
        professionalId: 'p6',
        title: 'Aula de Conversação em Inglês (Individual)',
        description: 'Prática 100% conversacional focada nos seus objetivos profissionais ou de viagem.',
        category: 'Aulas',
        price: 80,
        duration: 60,
      },
      {
        id: 's6-2',
        professionalId: 'p6',
        title: 'Preparatório para Entrevistas de Emprego',
        description: 'Treinamento de perguntas difíceis, pitch pessoal e vocabulário técnico em inglês.',
        category: 'Aulas',
        price: 120,
        duration: 60,
      },
      {
        id: 's6-3',
        professionalId: 'p6',
        title: 'Pacote Mensal de Aulas (4 sessões)',
        description: 'Plano estruturado com material didático digital e acompanhamento contínuo.',
        category: 'Aulas',
        price: 290,
        duration: 240,
      },
    ],
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'r1',
    professionalId: 'p1',
    clientId: 'u101',
    clientName: 'Fernanda Rocha',
    rating: 5,
    text: 'A Maria foi incrível! Fez uma faxina impecável e deixou tudo extremamente perfumado e organizado. Com certeza contratarei novamente.',
    createdAt: '2026-08-10T14:30:00Z',
  },
  {
    id: 'r2',
    professionalId: 'p1',
    clientId: 'u102',
    clientName: 'Rodrigo Alves',
    rating: 5,
    text: 'Muito pontual e caprichosa. A organização do closet ficou perfeita!',
    createdAt: '2026-08-18T10:15:00Z',
  },
  {
    id: 'r3',
    professionalId: 'p2',
    clientId: 'u103',
    clientName: 'Patricia Lima',
    rating: 5,
    text: 'O Carlos resolveu um vazamento antigo no banheiro que outros não conseguiam achar. Muito profissional e honesto.',
    createdAt: '2026-08-12T16:45:00Z',
  },
  {
    id: 'r4',
    professionalId: 'p2',
    clientId: 'u104',
    clientName: 'Gabriel Siqueira',
    rating: 5,
    text: 'Instalou as tomadas novas e trocou o chuveiro rapidamente. Preço justo e trabalho de qualidade.',
    createdAt: '2026-08-20T11:20:00Z',
  },
  {
    id: 'r5',
    professionalId: 'p3',
    clientId: 'u105',
    clientName: 'Camila Duarte',
    rating: 5,
    text: 'Minhas sobrancelhas nunca ficaram tão harmônicas. O atendimento da Juliana é maravilhoso e muito detalhista!',
    createdAt: '2026-08-15T09:00:00Z',
  },
  {
    id: 'r6',
    professionalId: 'p4',
    clientId: 'u106',
    clientName: 'Thiago Martins',
    rating: 5,
    text: 'Degradê na régua e a barboterapia é relaxante demais. Atendimento nota 10.',
    createdAt: '2026-08-22T18:00:00Z',
  },
  {
    id: 'r7',
    professionalId: 'p5',
    clientId: 'u107',
    clientName: 'Larissa Mendes',
    rating: 5,
    text: 'Rafael salvou todos os meus arquivos e o computador ficou muito mais rápido com o SSD novo. Recomendo muito!',
    createdAt: '2026-08-14T15:30:00Z',
  },
  {
    id: 'r8',
    professionalId: 'p6',
    clientId: 'u108',
    clientName: 'Bruno Henrique',
    rating: 5,
    text: 'As aulas com a Beatriz me deram a confiança que eu precisava para a entrevista em inglês. Fui aprovado na vaga!',
    createdAt: '2026-08-21T17:10:00Z',
  },
];
